openai:
  api_key: 'your openai api key'

discord:
  token: 'your discord token'
  midjourney_bot:
    app_id: '936929561302675456'
    ch_id: 'your discord channel id'
    session_id: 'your discord session id'
    token: 'your midjourney bot token'